### ISSUE TITLE
Webber

### ISSUE THREAD

**Issue by nonfungibletunji** [swifweb/webber#1]
Suspicious process “webber”!
The process has no code signature. This means that the developer is anonymous and their real-life identity cannot be determined..

**Comment by MihaelIsaev** [comment]
What’s that? Never heard anything like that before 🙂 When you install webber via homebrew  it compiles from sources on your machine. Another way is to just clone webber and compile it manually using `swift build -c release` and then use compiled binary and be totally safe 🙂

**Comment by MihaelIsaev** [comment]
Similar issue https://github.com/pawelsalawa/sqlitestudio/issues/3509 it is just common warning for unsigned open-source apps.

**Comment by nonfungibletunji** [comment]
Thanks

S Tunji Turner
