### ISSUE TITLE
Cannot perform DataView.prototype.setBigUint64 on a detached ArrayBuffer

### ISSUE THREAD

**Issue by kateinoigakukun** [swifweb/webber#2]
Forward https://github.com/swiftwasm/JavaScriptKit/issues/217

Could you apply the patch for `wasmer-js/wasi` https://github.com/swiftwasm/carton/blob/74b8ca6e1d5ebef70ff6ecebf445b5a9674f83a1/entrypoint/common.js#L135-L152, or you can use [uwasi](https://github.com/swiftwasm/uwasi) instead of it.

**Comment by MihaelIsaev** [comment]
@kateinoigakukun thank you very much, I applied the patch! 🚀 (swiftwasm/JavaScriptKit#217)

@tierracero could you please update webber to 1.4.0 via `brew upgrade webber` to check if issue is solved?

**Comment by tierracero** [comment]
Thanks for forwarding issue to the SwifWeb team, they made a fix that you suggested. 
I have been doing various stress tests and everything seems to be working fine now.
